### ISSUE TITLE
human readable citations for specimen 9d0163c5-090f-11e3-af8d-50faf7e7a06b

### ISSUE THREAD

**Issue by jhpoelen** [ekrimmel/paleo-interactions-test#1]
@ekrimmel thanks for sharing your species interactions based on fossil records. Very exciting! 

I noticed that you are using occurenceIds like 9d0163c5-090f-11e3-af8d-50faf7e7a06b to point to specific (fossil) specimen (e.g., 9d0163c5-090f-11e3-af8d-50faf7e7a06b) . Also, I noticed that for 9d0163c5-090f-11e3-af8d-50faf7e7a06b, the columns referenceUrl, referenceCitation were left empty. 

If you populate these fields with specimen landing pages, then it would be easier for folks to find your specimen records. 

Also, I was wondering whether adding the catalog number (e.g., sourceCatalogNumber), collection code (sourceCollectionCode) and institution codes (sourceInstitutionCode) for the specimen would help the discoverability of the referenced evidence. 

Curious to hear your thoughts,
-jorrit

btw - as you probably noticed, your dataset passed the GloBI automated review at https://app.travis-ci.com/github/ekrimmel/paleo-interactions-test/builds/237146737#L190 and https://github.com/ekrimmel/paleo-interactions-test/runs/3539114005#step:4:4 - 

```
  _____ _       ____ _____   _____            _                
  / ____| |     |  _ \_   _| |  __ \          (_)               
 | |  __| | ___ | |_) || |   | |__) |_____   ___  _____      __ 
 | | |_ | |/ _ \|  _ < | |   |  _  // _ \ \ / / |/ _ \ \ /\ / / 
 | |__| | | (_) | |_) || |_  | | \ \  __/\ V /| |  __/\ V  V /  
  \_____|_|\___/|____/_____| |_|  \_\___| \_/ |_|\___| \_/\_/   
 | |           |  ____| | |                                     
 | |__  _   _  | |__  | | |_ ___  _ __                          
 | '_ \| | | | |  __| | | __/ _ \| '_ \                         
 | |_) | |_| | | |____| | || (_) | | | |                        
 |_.__/ \__, | |______|_|\__\___/|_| |_|                        
         __/ |                                                  
        |___/                                                   

Miller 3.4.0
s3cmd version 2.1.0
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
elton not found... installing from [https://github.com/globalbioticinteractions/elton/releases/download/0.11.1/elton.jar]
elton version 0.11.1

Review of [local] started at [2021-09-07T23:29:07+00:00].

updating [local]... done.
creating review [local]... done.
listing interactions [local]... done.
listing taxa [local]... done.
listing nanopubs [local]... done.

Review of [ekrimmel/paleo-interactions-test] included:
  - 5 interaction(s)
  - 0 note(s)
  - 5 info(s)

Hurray! [ekrimmel/paleo-interactions-test] passed the GloBI review.

```

**Comment by ekrimmel** [comment]
Great suggestions @jhpoelen! I added values to the referenceURL and referenceCitation fields where there were none (see 9e8b180c0a41daffcfc148593d72059cbbb1ef94), but this is something we had questions about when we were compiling this test data. The specimen (or a digital record representing the specimen) seems like a good reference to cite, but what about interactions that are supported by both a specimen and a publication (e.g. our 9a887a47-090f-11e3-af8d-50faf7e7a06b)? Are the reference fields repeatable?

Is GloBI already supporting fields for catalog number (e.g., sourceCatalogNumber), collection code (sourceCollectionCode) and institution codes (sourceInstitutionCode)? Or are you wondering if those might be worth supporting in the future? I think this is a good topic for discussion in tomorrow's Happy Hour!

**Comment by jhpoelen** [comment]
Citations are looking much better now! Apologies for taking over 1.5 years to respond

![Screenshot from 2023-04-10 09-13-06](https://user-images.githubusercontent.com/1084872/230920778-4605ceec-5758-471a-83c2-04bb7ad47fbd.png)

**Comment by jhpoelen** [comment]
![image](https://user-images.githubusercontent.com/1084872/230920902-11bc8e19-f46c-42b8-9584-9756b6fd69f5.png)
